require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/**/*
