name: Lint
on: push

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: yamat47/github-toolkit/actions/checkout@main
        with:
          persist-credentials: false
      - name: Lint workflows
        run: make lint
